//! Writes `src/Tables.mw` and `src/Cases.mw` for semver.
//!
//! ```text
//! cargo run --release -- <package root>
//! ```
//!
//! * **Tables** -- which characters Rust's `{:?}` writes as `\u{…}`, since
//!   semver's error messages quote characters that way.
//! * **Cases** -- strings parsed as versions, requirements, comparators,
//!   pre-release and build identifiers, with what the crate makes of each; and
//!   pairs compared and matched. The strings are every literal in the crate's
//!   tests, and more built at random.
//!
//! The library itself is ported by hand into `src/`, and its source is
//! fingerprinted.

use semver::{BuildMetadata, Comparator, Op, Prerelease, Version, VersionReq};
use std::cmp::Ordering;
use std::fmt::Write as _;
use std::path::PathBuf;

const SCALARS: u32 = 0x11_0000;

/// The crate version pinned in `Cargo.toml`.
const UPSTREAM_VERSION: &str = "1.0.28";

/// The fingerprint of the crate's source, which `src/` ports.
const SOURCES: u64 = 0x23c3_cedb_93b2_39b0;

fn main() {
    let root = PathBuf::from(std::env::args().nth(1).unwrap_or_else(|| "../..".into()));

    let print = fingerprint(include_str!(concat!(env!("OUT_DIR"), "/sources.rs.txt")));
    if print != SOURCES {
        eprintln!(
            "error: semver is not the version src/ ports.\n\
             Compare its source in {} with the previous version, carry any change\n\
             into src/, then set SOURCES in scripts/generate/src/main.rs to\n\
             {print:#x}",
            env!("UPSTREAM_DIR")
        );
        std::process::exit(1);
    }

    let tables = tables();
    let tables_path = root.join("src/Tables.mw");
    std::fs::write(&tables_path, &tables).unwrap();
    eprintln!("wrote {} ({} bytes)", tables_path.display(), tables.len());

    let cases = cases();
    let cases_path = root.join("src/Cases.mw");
    std::fs::write(&cases_path, &cases).unwrap();
    eprintln!("wrote {} ({} bytes)", cases_path.display(), cases.len());
}

/// FNV-1a: stable across builds, which `DefaultHasher` does not promise.
fn fingerprint(text: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in text.bytes() {
        h ^= u64::from(b);
        h = h.wrapping_mul(0x0100_0000_01b3);
    }
    h
}

// --- encoding -----------------------------------------------------------------------

/// A number as `digits` base-64 digits, most significant first, each digit the
/// character `'0' + d`: `'0'` to `'o'`, one contiguous run of ASCII.
fn digits(out: &mut String, value: u64, digits: u32) {
    assert!(
        value < 1 << (6 * digits),
        "{value} does not fit in {digits} digits"
    );
    for k in (0..digits).rev() {
        out.push(char::from(b'0' + ((value >> (6 * k)) & 63) as u8));
    }
}

/// A string, as its length in bytes (3 digits) and then its bytes.
fn text(out: &mut String, s: &str) {
    digits(out, s.len() as u64, 3);
    out.push_str(s);
}

/// `text` as one Meadow string literal, broken with `\`-newline every `width`
/// characters. Only printable ASCII is written raw; a space that would start a
/// line is `\x20`, since a continuation drops leading whitespace.
fn long_literal(text: &str, width: usize) -> String {
    let mut out = String::with_capacity(text.len() + text.len() / width * 4 + 2);
    out.push('"');
    for (i, c) in text.chars().enumerate() {
        let line_start = i > 0 && i % width == 0;
        if line_start {
            out.push_str("\\\n    ");
        }
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            ' ' if line_start => out.push_str("\\x20"),
            ' '..='~' => out.push(c),
            _ => {
                let _ = write!(out, "\\u{{{:X}}}", u32::from(c));
            }
        }
    }
    out.push('"');
    out
}

const HEADER: &str = "\
-- Copyright David Tolnay, and the Meadow port's authors. Dual-licensed under
-- Apache-2.0 or MIT: see COPYRIGHT.";

// --- tables -------------------------------------------------------------------------

fn tables() -> String {
    let mut runs: Vec<(u32, u32)> = Vec::new();
    for cp in 0..SCALARS {
        let Some(c) = char::from_u32(cp) else {
            continue;
        };
        if !format!("{c:?}").starts_with("'\\u{") {
            continue;
        }
        match runs.last_mut() {
            Some((_, hi)) if *hi + 1 == cp || (*hi == 0xD7FF && cp == 0xE000) => *hi = cp,
            _ => runs.push((cp, cp)),
        }
    }
    let mut body = String::new();
    for (lo, hi) in runs {
        digits(&mut body, lo.into(), 4);
        digits(&mut body, hi.into(), 4);
    }
    let (maj, min, pat) = char::UNICODE_VERSION;
    format!(
        "-- GENERATED by scripts/generate.sh for semver {UPSTREAM_VERSION}.
-- Do not edit: run the script again instead.
--
{HEADER}

-- The characters Rust's `{{:?}}` writes as `\\u{{…}}` (Unicode {maj}.{min}.{pat}):
-- those that are not printable, and combining marks. As `lo hi` ranges, 4
-- base-64 digits each: '0' ('0' + 0) to 'o' ('0' + 63), most significant
-- first.
@pub(pkg) def escaped =
  {}
",
        long_literal(&body, 96)
    )
}

// --- cases --------------------------------------------------------------------------

/// A small deterministic generator, so that the cases are the same on every run.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // xorshift64*
        self.0 ^= self.0 >> 12;
        self.0 ^= self.0 << 25;
        self.0 ^= self.0 >> 27;
        self.0.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }

    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }

    fn pick<T: Copy>(&mut self, xs: &[T]) -> T {
        xs[self.below(xs.len())]
    }

    fn chance(&mut self, percent: usize) -> bool {
        self.below(100) < percent
    }
}

/// Every string literal in `source`, escapes resolved.
fn string_literals(source: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut chars = source.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '/' && chars.peek() == Some(&'/') {
            for c in chars.by_ref() {
                if c == '\n' {
                    break;
                }
            }
            continue;
        }
        if c == '\'' {
            // A char literal, which may be '"'; skip it.
            let mut s = String::new();
            for c in chars.by_ref() {
                if c == '\'' && !s.ends_with('\\') {
                    break;
                }
                s.push(c);
                if s.len() > 4 {
                    break;
                }
            }
            continue;
        }
        if c != '"' {
            continue;
        }
        let mut s = String::new();
        while let Some(c) = chars.next() {
            match c {
                '"' => break,
                '\\' => match chars.next() {
                    Some('n') => s.push('\n'),
                    Some('t') => s.push('\t'),
                    Some('0') => s.push('\0'),
                    Some('u') => {
                        let hex: String =
                            chars.by_ref().skip(1).take_while(|c| *c != '}').collect();
                        s.push(char::from_u32(u32::from_str_radix(&hex, 16).unwrap()).unwrap());
                    }
                    Some(other) => s.push(other),
                    None => {}
                },
                _ => s.push(c),
            }
        }
        out.push(s);
    }
    out
}

const PIECES: &[&str] = &[
    "0",
    "1",
    "2",
    "9",
    "10",
    "01",
    "00",
    "123",
    "18446744073709551615",
    "18446744073709551616",
    "99999999999999999999",
    ".",
    ".",
    ".",
    "-",
    "+",
    "*",
    "x",
    "X",
    "^",
    "~",
    "=",
    ">",
    "<",
    ">=",
    "<=",
    "~>",
    ",",
    ", ",
    " ",
    "  ",
    "alpha",
    "beta",
    "rc",
    "a",
    "Z",
    "-x",
    "0a",
    "a0",
    "build",
    "sha",
    "5114f85",
    "é",
    "\u{0}",
    "\u{301}",
    "\n",
    "'",
    "\\",
    "\u{1F600}",
    "\u{7f}",
    "_",
    "v",
    "\"",
    "\t",
    "\u{200b}",
];

fn random_string(rng: &mut Rng) -> String {
    let n = 1 + rng.below(9);
    (0..n).map(|_| rng.pick(PIECES)).collect()
}

/// A version that parses, with a mix of pre-release and build parts.
fn random_version(rng: &mut Rng) -> String {
    let num = |rng: &mut Rng| rng.pick(&["0", "1", "2", "3", "10", "18446744073709551615"]);
    // A leading zero is allowed in build metadata, not in a pre-release.
    let pre = |rng: &mut Rng| {
        rng.pick(&[
            "0", "1", "2", "10", "alpha", "beta", "a", "a-b", "-", "Z", "rc1",
        ])
    };
    let ident = |rng: &mut Rng| {
        rng.pick(&[
            "0", "1", "2", "10", "01", "001", "alpha", "a", "a-b", "-", "Z",
        ])
    };
    let mut s = format!("{}.{}.{}", num(rng), num(rng), num(rng));
    if rng.chance(50) {
        let parts: Vec<&str> = (0..1 + rng.below(3)).map(|_| pre(rng)).collect();
        s.push('-');
        s.push_str(&parts.join("."));
    }
    if rng.chance(30) {
        let parts: Vec<&str> = (0..1 + rng.below(3)).map(|_| ident(rng)).collect();
        s.push('+');
        s.push_str(&parts.join("."));
    }
    s
}

/// A requirement that probably parses.
fn random_req(rng: &mut Rng) -> String {
    let n = 1 + rng.below(3);
    let parts: Vec<String> = (0..n)
        .map(|_| {
            let op = rng.pick(&["", "=", ">", ">=", "<", "<=", "~", "^", " ", ">= "]);
            let v = match rng.below(6) {
                0 => rng.pick(&["0", "1", "2"]).to_string(),
                1 => format!(
                    "{}.{}",
                    rng.pick(&["0", "1"]),
                    rng.pick(&["0", "1", "2", "*"])
                ),
                2 => format!("{}.*", rng.pick(&["0", "1"])),
                3 => format!("{}.{}.*", rng.pick(&["0", "1"]), rng.pick(&["0", "1"])),
                _ => random_version(rng),
            };
            format!("{op}{v}")
        })
        .collect();
    let sep = rng.pick(&[",", ", ", " ,", " , "]);
    parts.join(sep)
}

fn ord(o: Ordering) -> u64 {
    match o {
        Ordering::Less => 0,
        Ordering::Equal => 1,
        Ordering::Greater => 2,
    }
}

fn op_index(op: Op) -> u64 {
    match op {
        Op::Exact => 0,
        Op::Greater => 1,
        Op::GreaterEq => 2,
        Op::Less => 3,
        Op::LessEq => 4,
        Op::Tilde => 5,
        Op::Caret => 6,
        Op::Wildcard => 7,
        _ => unreachable!(),
    }
}

fn opt(out: &mut String, v: Option<u64>) {
    match v {
        Some(n) => text(out, &n.to_string()),
        None => text(out, "-"),
    }
}

fn comparator(out: &mut String, c: &Comparator) {
    digits(out, op_index(c.op), 1);
    text(out, &c.major.to_string());
    opt(out, c.minor);
    opt(out, c.patch);
    text(out, c.pre.as_str());
    text(out, &c.to_string());
}

/// A parse result: `1` and what `ok` writes, or `0` and the error message.
fn result<T, E: std::fmt::Display>(
    out: &mut String,
    r: Result<T, E>,
    ok: impl FnOnce(&mut String, T),
) {
    match r {
        Ok(v) => {
            digits(out, 1, 1);
            ok(out, v);
        }
        Err(e) => {
            digits(out, 0, 1);
            text(out, &e.to_string());
        }
    }
}

fn cases() -> String {
    let mut rng = Rng(0x5e3e_7a4a_c0ff_ee42);
    let literals = string_literals(include_str!(concat!(env!("OUT_DIR"), "/tests.rs.txt")));

    let mut strings: Vec<String> = literals.clone();
    for _ in 0..1500 {
        strings.push(random_string(&mut rng));
    }
    for _ in 0..500 {
        strings.push(random_version(&mut rng));
        strings.push(random_req(&mut rng));
    }
    strings.push(String::new());
    strings.sort();
    strings.dedup();

    let mut body = String::new();
    let mut counts = [0usize; 4];

    // Kind 0: one string, parsed each way.
    for s in &strings {
        counts[0] += 1;
        digits(&mut body, 0, 1);
        text(&mut body, s);
        result(&mut body, Version::parse(s), |out, v| {
            text(out, &v.major.to_string());
            text(out, &v.minor.to_string());
            text(out, &v.patch.to_string());
            text(out, v.pre.as_str());
            text(out, v.build.as_str());
            text(out, &v.to_string());
        });
        result(&mut body, VersionReq::parse(s), |out, r| {
            digits(out, r.comparators.len() as u64, 2);
            for c in &r.comparators {
                comparator(out, c);
            }
            text(out, &r.to_string());
        });
        result(&mut body, Comparator::parse(s), |out, c| {
            comparator(out, &c)
        });
        result(&mut body, Prerelease::new(s), |out, p| {
            text(out, p.as_str())
        });
        result(&mut body, BuildMetadata::new(s), |out, b| {
            text(out, b.as_str())
        });
    }

    // The versions and requirements that parse.
    let mut versions: Vec<Version> = strings
        .iter()
        .filter_map(|s| Version::parse(s).ok())
        .collect();
    for _ in 0..300 {
        versions.push(Version::parse(&random_version(&mut rng)).unwrap());
    }
    let reqs: Vec<(String, VersionReq)> = strings
        .iter()
        .filter_map(|s| VersionReq::parse(s).ok().map(|r| (s.clone(), r)))
        .collect();

    // Kind 1: two versions compared.
    for _ in 0..3000 {
        let a = &versions[rng.below(versions.len())];
        let b = if rng.chance(10) {
            a
        } else {
            &versions[rng.below(versions.len())]
        };
        counts[1] += 1;
        digits(&mut body, 1, 1);
        text(&mut body, &a.to_string());
        text(&mut body, &b.to_string());
        digits(&mut body, ord(a.cmp(b)), 1);
        digits(&mut body, ord(a.cmp_precedence(b)), 1);
        digits(&mut body, ord(a.pre.cmp(&b.pre)), 1);
        digits(&mut body, ord(a.build.cmp(&b.build)), 1);
    }

    // Kind 2: a requirement matched against a version, and each of its
    // comparators too.
    for _ in 0..4000 {
        let (s, r) = &reqs[rng.below(reqs.len())];
        let v = &versions[rng.below(versions.len())];
        counts[2] += 1;
        digits(&mut body, 2, 1);
        text(&mut body, s);
        text(&mut body, &v.to_string());
        digits(&mut body, u64::from(r.matches(v)), 1);
        digits(&mut body, r.comparators.len() as u64, 2);
        for c in &r.comparators {
            digits(&mut body, u64::from(c.matches(v)), 1);
        }
    }

    // Kind 2 again: the requirements and versions the crate's own tests use,
    // matched against each other -- a sample, as there are many pairs.
    let test_reqs: Vec<(&String, VersionReq)> = literals
        .iter()
        .filter_map(|s| VersionReq::parse(s).ok().map(|r| (s, r)))
        .collect();
    let test_versions: Vec<Version> = literals
        .iter()
        .filter_map(|v| Version::parse(v).ok())
        .collect();
    for _ in 0..3000 {
        let (s, r) = &test_reqs[rng.below(test_reqs.len())];
        let v = &test_versions[rng.below(test_versions.len())];
        counts[3] += 1;
        digits(&mut body, 2, 1);
        text(&mut body, s);
        text(&mut body, &v.to_string());
        digits(&mut body, u64::from(r.matches(v)), 1);
        digits(&mut body, r.comparators.len() as u64, 2);
        for c in &r.comparators {
            digits(&mut body, u64::from(c.matches(v)), 1);
        }
    }

    let mut out = String::new();
    let _ = writeln!(
        out,
        "-- GENERATED by scripts/generate.sh from semver {UPSTREAM_VERSION}.
-- Do not edit: run the script again instead.
--
-- Inputs, with what semver makes of them, for `Tests.mw`: {} strings parsed
-- every way, {} pairs of versions compared, and {} versions matched against
-- requirements.
--
{HEADER}

-- Each case starts with its kind (1 base-64 digit), and its fields follow in
-- the order `Tests.mw` reads them. A string is its length in bytes (3 digits)
-- and then its bytes; a parse is 1 and its result, or 0 and the error
-- message; an ordering is 0, 1 or 2 for less, equal or greater.
@cfg(test)
@pub(pkg) def cases =
  {}",
        counts[0],
        counts[1],
        counts[2] + counts[3],
        long_literal(&body, 96)
    );
    out
}
